In [70]:
import numpy as np

In [71]:
np.__version__

'2.2.2'

## Create & Read

#### 1D Array

In [73]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [74]:
type(arr1)

numpy.ndarray

In [76]:
arr1.shape

(5,)

In [78]:
arr1.dtype

dtype('int64')

In [79]:
arr1.ndim

1

In [81]:
arr1.size

5

#### 2D Array

In [83]:
arr2 = np.array([[1,4,9], [2,3,7]])

In [84]:
arr2

array([[1, 4, 9],
       [2, 3, 7]])

In [86]:
arr2.ndim

2

In [87]:
arr2.dtype

dtype('int64')

In [88]:
type(arr2)

numpy.ndarray

In [89]:
arr2.size

6

In [90]:
arr2.shape

(2, 3)

#### 3D Array

In [99]:
arr3 = np.array([[[1,4,9],[2,3,7]],[[3,5,4],[5,8,7]], [[1,4,9], [2,3,7]]])

In [100]:
arr3.ndim

3

In [101]:
arr3.shape

(3, 2, 3)

In [102]:
arr3

array([[[1, 4, 9],
        [2, 3, 7]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 9],
        [2, 3, 7]]])

In [103]:
arr3.size

18

In [104]:
arr3.dtype

dtype('int64')

In [105]:
type(arr3)

numpy.ndarray

### Create Random Array

In [107]:
randomArr = np.random.rand(3,2,3)
randomArr

array([[[0.00629899, 0.10005018, 0.41383009],
        [0.94480479, 0.46493843, 0.23705425]],

       [[0.28432266, 0.28617537, 0.09244939],
        [0.02942447, 0.49488777, 0.89136417]],

       [[0.61009103, 0.68268143, 0.67487353],
        [0.0341294 , 0.59912563, 0.22891359]]])

In [108]:
randomArr.dtype

dtype('float64')

In [109]:
zeros = np.zeros((3,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [110]:
zeros.ndim

3

In [111]:
full = np.full((3,2,3), 9)
full

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])

In [113]:
ones = np.ones((3,2,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [114]:
arr3

array([[[1, 4, 9],
        [2, 3, 7]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 9],
        [2, 3, 7]]])

In [115]:
arr3[0]

array([[1, 4, 9],
       [2, 3, 7]])

In [117]:
arr3[1][0][1]

np.int64(5)

In [119]:
arr3[1,0,1]

np.int64(5)

### update & delete

In [120]:
a1 = np.random.rand(2,3,2)
a2 = np.random.rand(2,3,2)

In [121]:
a1

array([[[0.27181471, 0.92989148],
        [0.03530772, 0.13582423],
        [0.76447306, 0.41516236]],

       [[0.37734487, 0.59012153],
        [0.54029336, 0.18540925],
        [0.19410625, 0.15000395]]])

In [122]:
a2

array([[[0.95016633, 0.63715524],
        [0.93119048, 0.73127987],
        [0.72021459, 0.03803785]],

       [[0.49842134, 0.60701564],
        [0.4639026 , 0.42018872],
        [0.53396642, 0.97759856]]])

#### Basic Math Operations

In [123]:
np.add(a1,a2)

array([[[1.22198104, 1.56704672],
        [0.96649821, 0.8671041 ],
        [1.48468765, 0.45320021]],

       [[0.87576621, 1.19713717],
        [1.00419596, 0.60559797],
        [0.72807268, 1.12760251]]])

In [125]:
np.subtract(a1,a2)

array([[[-0.67835162,  0.29273623],
        [-0.89588276, -0.59545564],
        [ 0.04425846,  0.37712451]],

       [[-0.12107647, -0.01689411],
        [ 0.07639077, -0.23477947],
        [-0.33986017, -0.82759462]]])

In [126]:
np.divide(a1,a2)

array([[[ 0.28607066,  1.45944256],
        [ 0.03791676,  0.18573495],
        [ 1.06145177, 10.91445318]],

       [[ 0.75708008,  0.97216857],
        [ 1.16466984,  0.44125233],
        [ 0.36351771,  0.15344125]]])

In [127]:
np.multiply(a1,a2)

array([[[0.25826918, 0.59248523],
        [0.03287822, 0.09932553],
        [0.55058465, 0.01579188]],

       [[0.18807674, 0.358213  ],
        [0.25064349, 0.07790688],
        [0.10364622, 0.14664365]]])

#### statistical operations

In [137]:
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,8)
log = np.log(25)
mi = np.min(a1)
ma = np.max(a2)

In [129]:
sqrt

np.float64(5.0)

In [133]:
ab

np.int64(2)

In [134]:
power

np.int64(256)

In [135]:
log

np.float64(3.2188758248682006)

In [138]:
mi

np.float64(0.035307722738488034)

In [139]:
ma

np.float64(0.9775985642185443)

#### update

In [140]:
arr3

array([[[1, 4, 9],
        [2, 3, 7]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 9],
        [2, 3, 7]]])

In [141]:
arr3[0,0,2] = 500
arr3

array([[[  1,   4, 500],
        [  2,   3,   7]],

       [[  3,   5,   4],
        [  5,   8,   7]],

       [[  1,   4,   9],
        [  2,   3,   7]]])

In [142]:
arr3.sort()
arr3

array([[[  1,   4, 500],
        [  2,   3,   7]],

       [[  3,   4,   5],
        [  5,   7,   8]],

       [[  1,   4,   9],
        [  2,   3,   7]]])

In [143]:
arr3.shape

(3, 2, 3)

In [145]:
arr3_reshape = arr3.reshape(2,3,3)
arr3_reshape

array([[[  1,   4, 500],
        [  2,   3,   7],
        [  3,   4,   5]],

       [[  5,   7,   8],
        [  1,   4,   9],
        [  2,   3,   7]]])

In [147]:
arr3_reshape.shape

(2, 3, 3)

#### appending & inserting

In [150]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [152]:
new_array = np.ones((3,2,3))
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [154]:
appd = np.append(zeros, new_array, axis=0)
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [157]:
inserted_array = np.insert(zeros, 2, new_array, axis=0)
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [158]:
arr4 = np.random.rand(3,2,3)
arr4

array([[[0.43302723, 0.80724125, 0.27691321],
        [0.51964867, 0.93098031, 0.80995854]],

       [[0.82551259, 0.68274897, 0.5129549 ],
        [0.39122618, 0.47624087, 0.42078271]],

       [[0.32103512, 0.4988283 , 0.83471943],
        [0.41903877, 0.04071046, 0.34303131]]])

In [159]:
arr5 = np.delete(arr4, 0, axis=1)
arr5

array([[[0.51964867, 0.93098031, 0.80995854]],

       [[0.39122618, 0.47624087, 0.42078271]],

       [[0.41903877, 0.04071046, 0.34303131]]])

In [161]:
np.save('new_array', arr5)

In [162]:
np.load('new_array.npy')

array([[[0.51964867, 0.93098031, 0.80995854]],

       [[0.39122618, 0.47624087, 0.42078271]],

       [[0.41903877, 0.04071046, 0.34303131]]])